// vue/src/components/EquipmentTable.vue
<template>
  <Toolbar>
    <template #start>
      <Button
        label="Добавить"
        icon="pi pi-plus"
        class="p-button bg-blue-400 mr-3"
        @click="addEquipment()"
      />
      <Button
        label="Удалить выбранное"
        icon="pi pi-trash"
        class="p-button-danger"
        :disabled="isEmpty"
        @click="deleteSelected"
      />
    </template>
  </Toolbar>
  <DataTable
    :value="data"
    :paginator="true"
    :rows="10"
    dataKey="id"
    :rowHover="true"
    filterDisplay="menu"
    :loading="loading"
    v-model:selection="selectedRows"
    paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
    :rowsPerPageOptions="[10, 25, 50]"
    currentPageReportTemplate="Showing {first} to {last} of {totalRecords} entries"
    responsiveLayout="scroll"
  >
    <template #header>
      <div class="flex justify-between items-center">
        <h5 class="m-0">МТО</h5>
        <span class="p-input-icon-left">
          <i class="pi pi-search" />
          <InputText placeholder="Keyword Search" />
        </span>
      </div>
    </template>
    <template #empty> Нет оборудования </template>
    <template #loading> Загрузка... </template>
    <Column selectionMode="multiple" headerStyle="width: 3rem"></Column>
    <Column field="id" header="№" sortable></Column>
    <Column field="name" header="Название" sortable></Column>
    <Column field="type" header="Тип" sortable></Column>
    <Column
      headerStyle="width: 4rem; text-align: center"
      bodyStyle="display:flex;text-align: center; overflow: visible"
    >
      <template #body>
        <Button
          icon="pi pi-eye"
          className="p-button-rounded p-button-primary mr-2"
        />
        <Button
          icon="pi pi-pencil"
          className="p-button-rounded p-button-success mr-2"
        />
        <Button
          icon="pi pi-trash"
          className="p-button-rounded p-button-danger"
        />
      </template>
    </Column>
  </DataTable>
  <Dialog header="Добавить МТО" v-model:visible="isDialogOpen" :modal="true">
    <div class="flex flex-col">
      <div class="flex flex-col mb-4">
      <label htmlFor="name">Наименование МТО</label>
      <InputText id="name" v-model="newEquipment.name" required autoFocus />
    </div>
    <div class="flex flex-col">
      <label htmlFor="type">Тип</label>
      <Dropdown v-model="newEquipment.type" :options="types" placeholder="Выберите тип МТО" />
    </div>
    </div>
    
    <template  #footer>
		<Button label="Отмена" icon="pi pi-times" class="p-button-text"/>
    <Button label="Сохранить" icon="pi pi-check" @click="addNewEquipment" class="p-button-success" autofocus />
	</template>
  </Dialog>
</template>

<script>
import DataTable from "primevue/datatable";
import Column from "primevue/column";
import InputText from "primevue/inputtext";
import Button from "primevue/button";
import Dialog from "primevue/dialog";
import Toolbar from "primevue/toolbar";
import Dropdown from 'primevue/dropdown';
import { FilterMatchMode, FilterOperator } from "primevue/api";
import { ref, computed } from "vue";
export default {
  components: {
    DataTable,
    Column,
    InputText,
    Button,
    Dialog,
    Toolbar,
    Dropdown,
  },
  setup() {
    const isEmpty = computed(() => {
  return selectedRows === null; 
})
    const types=["АО","ПО"];
    const equipmentTemplate={
      name:'',
      type:null,
    }
    const isDialogOpen = ref(true);
    const loading = ref(true);
    const newEquipment=ref({
      name:'',
      type:null,
    })
    const selectedRows = ref();
    const data = ref([]);
    for (let i = 0; i < 4; i++) {
      data.value.push({
        id: i + 1,
        name: `Обеспечение${i + 1}`,
        type: Math.random() > 0.5 ? "ПО" : "АО",
      });
    }
    loading.value = false;
    const addEquipment = () => {
      isDialogOpen.value = true;
    };
    const addNewEquipment = () => {
      data.value.push(newEquipment.value);
      newEquipment.value=equipmentTemplate;
      isDialogOpen.value=false;
    };
    const deleteSelected=()=>{
      data.value=data.value.filter(eq => !selectedRows.value.includes(eq))
    }
    return {
      data,
      loading,
      selectedRows,
      isDialogOpen,
      addEquipment,
      newEquipment,
      addNewEquipment, 
      types,
      deleteSelected,
      isEmpty
    };
  },
};
</script>

<style>
button {
  background-color: rgb(143, 73, 73);
}
</style>

// src/components/EquipmentTable.tsx
import React, { useEffect, useMemo } from 'react';
import { DataTable, DataTableFilterMeta } from 'primereact/datatable';
import { Column, ColumnFilterElementTemplateOptions } from 'primereact/column';
import { Button } from 'primereact/button';
import { InputText } from 'primereact/inputtext';
import { MultiSelect } from 'primereact/multiselect';
import { FilterMatchMode } from 'primereact/api';
import { MultiSelectChangeParams } from 'primereact/multiselect';
import { PaginatorCurrentPageReportOptions, PaginatorRowsPerPageDropdownOptions, PaginatorTemplate } from 'primereact/paginator';
import { Dropdown } from 'primereact/dropdown';
import { Toolbar } from 'primereact/toolbar';

function generateEquipmentData(count: number): EquipmentData[] {
    const data: EquipmentData[] = [];
    for (let i = 0; i < count; i++) {
        data.push({
            id: i + 1,
            name: `Обеспечение${i + 1}`,
            type: Math.random() > 0.5 ? 'ПО' : 'АО'
        });
    }
    return data;
}

export interface EquipmentData {
    id: number;
    name: string;
    type: string;
}


const EquipmentTable: React.FC = () => {
    const [data, setData] = React.useState<EquipmentData[]>(generateEquipmentData(15));

    const [filters, setFilters] = React.useState<DataTableFilterMeta>({});
    const [globalFilterValue, setGlobalFilterValue] = React.useState<string>('');

    const types = useMemo(() => ['ПО', 'АО'], []);

    useEffect(() => {
        resetFilters();
    }, []);

    const resetFilters = () => {
        setFilters({
            'global': { value: null, matchMode: FilterMatchMode.CONTAINS },
            'name': { value: null, matchMode: FilterMatchMode.CONTAINS },
            'type': { value: null, matchMode: FilterMatchMode.IN },
        });
        setGlobalFilterValue('');
    }

    const onGlobalFilterChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const value = event.target.value;
        // FIXME: не стоит перезаписывать global полностью
        // Следует перезаписывать только его value
        const newFilters = { ...filters, 'global': { value, matchMode: FilterMatchMode.CONTAINS } };
        setFilters(newFilters);
        setGlobalFilterValue(value);
    }

    const typeFilterTemplate = (options: ColumnFilterElementTemplateOptions) => {
        return <MultiSelect display="chip" options={types}
            value={options.value} onChange={(e: MultiSelectChangeParams) => { options.filterApplyCallback(e.value); }}
            placeholder="Все" className="p-column-filter" />;
    }

    const leftToolbarTemplate = () => {
        return (
            <React.Fragment>
                <Button label="Добавить" icon="pi pi-plus" className="p-button-success mr-3" />
                <Button label="Удалить выбранное" icon="pi pi-trash" className="p-button-danger" />
            </React.Fragment>
        )
    }

    const renderHeader = () => {
        return (
            <div>
                <span className="p-input-icon-left">
                    <i className="pi pi-search" />
                    <InputText className='mr-3' value={globalFilterValue} onChange={onGlobalFilterChange} placeholder="Поиск..." />
                </span>
                <Button type="button" icon="pi pi-filter-slash" label="Очистить" onClick={resetFilters} />
            </div>
        )
    }

    const header = useMemo(() => renderHeader(), [globalFilterValue]);

    const paginatorTemplate: PaginatorTemplate = {
        layout: 'CurrentPageReport FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown',
        'RowsPerPageDropdown': (options: PaginatorRowsPerPageDropdownOptions) => {
            const dropdownOptions = [
                { label: 10, value: 10 },
                { label: 20, value: 20 },
                { label: 50, value: 50 },
                { label: 'Все', value: options.totalRecords },
            ];

            return <Dropdown value={options.value} options={dropdownOptions} onChange={options.onChange} />;
        },
        'CurrentPageReport': (options: PaginatorCurrentPageReportOptions) => {
            return (
                <span style={{ color: 'var(--text-color)', userSelect: 'none', width: '120px', textAlign: 'center' }}>
                    {options.first} - {options.last} из {options.totalRecords}
                </span>
            )
        },
        'FirstPageLink': (options) => {
            return options.element;
        },
        'LastPageLink': (options) => {
            return options.element;
        },
        'JumpToPageInput': (options) => {
            return options.element;
        },
        'NextPageLink': (options) => {
            return options.element;
        },
        'PrevPageLink': (options) => {
            return options.element;
        },
        'PageLinks': (options) => {
            return options.element;
        }
    };

    return (
        <>
            <Toolbar className="mb-3" left={leftToolbarTemplate}></Toolbar>

            <DataTable value={data}
                sortMode='multiple' removableSort
                header={header} responsiveLayout="scroll"
                resizableColumns columnResizeMode="fit"
                emptyMessage='МТО отсутствуют...' showGridlines dataKey='id'
                filterDisplay='row' filters={filters} globalFilterFields={['name', 'type']}
                paginator rows={10} paginatorTemplate={paginatorTemplate}>
                <Column field="id" header="#" sortable />
                <Column field="name" header="Название" sortable
                    filter filterPlaceholder='Поиск по названию...' showFilterMenu={false} />
                <Column field='type' header="Тип" sortable
                    filter filterElement={typeFilterTemplate} showFilterMenu={false} />
            </DataTable>
        </>
    );
}

export default EquipmentTable;
